# Data Collection and Preprocessing

## Importing libraries

In [ ]:
# Import necessary libraries
import requests
import pandas as pd
import numpy as np
import sys
!{sys.executable} -m pip install scikit-learn
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: pycountry_convert in /usr/local/lib/python3.10/dist-packages (0.7.2)
Requirement already satisfied: pprintpp>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (0.4.0)
Requirement already satisfied: pycountry>=16.11.27.1 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (24.6.1)
Requirement already satisfied: pytest>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (7.4.4)
Requirement already satisfied: pytest-mock>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (3.14.0)
Requirement already satisfied: pytest-cov>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (6.0.0)
Requirement already satisfied: repoze.lru>=0.7 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (0.7)
Requirement already satisfied: wheel>=0.30.0 in /usr/local/lib/python3.10/dist-packages (from pycountry_convert) (0.44.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest>=3.4.0->pycountry_convert) (2.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest>=3.4.0->pycountry_convert) (24.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest>=3.4.0->pycountry_convert) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest>=3.4.0->pycountry_convert) (1.2.2)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest>=3.4.0->pycountry_convert) (2.0.2)
Requirement already satisfied: coverage>=7.5 in /usr/local/lib/python3.10/dist-packages (from coverage[toml]>=7.5->pytest-cov>=2.5.1->pycountry_convert) (7.6.4)

**Explanation:** Imports essential libraries for data analysis (pandas, numpy) and visualization (matplotlib, seaborn). Installs scikit-learn, which is required for data preprocessing and modeling tasks. Sets up tools for feature encoding (LabelEncoder) and scaling (StandardScaler).

In [ ]:
# Load the newly uploaded CSV file and preview the data
csv_file_path = '/content/superstore_data.csv'
# Attempting to load the CSV with automatic delimiter inference and handling of irregular rows
superstore_data = pd.read_csv(csv_file_path, encoding='ISO-8859-1', sep=None, engine='python')

# Display the first few rows to understand its structure
superstore_data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08.11.16,11.11.16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,"261,96",2,0,"41,9136"
1,2,CA-2016-152156,08.11.16,11.11.16,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...","731,94",3,0,"219,582"
2,3,CA-2016-138688,12.06.16,16.06.16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,"14,62",2,0,"6,8714"
3,4,US-2015-108966,11.10.15,18.10.15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,"957,5775",5,"0,45","-383,031"
4,5,US-2015-108966,11.10.15,18.10.15,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,"22,368",2,"0,2","2,5164"

Dataset downloaded from "Sample Data" section in Tableau Public (https://public.tableau.com/app/learn/sample-data), called "EU Super Store".

In [ ]:
superstore_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   object
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   object
 20  Profit         9994 non-null   object
dtypes: int64(3), object(18)
memory usage: 1.6+ MB

## Data Conversion
- Date Conversion: Order Date and Ship Date are now in datetime format.
- Numeric Conversion: Sales, Profit, and Discount columns are now in float format, allowing for quantitative analysis.

In [ ]:
# Step 1: Convert 'Order Date' and 'Ship Date' to datetime format
superstore_data['Order Date'] = pd.to_datetime(superstore_data['Order Date'], errors='coerce', dayfirst=True)
superstore_data['Ship Date'] = pd.to_datetime(superstore_data['Ship Date'], errors='coerce', dayfirst=True)

# Step 2: Convert 'Sales', 'Profit', and 'Discount' to numeric types
# Replace commas with dots in the numeric columns for correct decimal interpretation
superstore_data['Sales'] = pd.to_numeric(superstore_data['Sales'].str.replace(',', '.'), errors='coerce')
superstore_data['Profit'] = pd.to_numeric(superstore_data['Profit'].str.replace(',', '.'), errors='coerce')
superstore_data['Discount'] = pd.to_numeric(superstore_data['Discount'].str.replace(',', '.'), errors='coerce')

# Display the cleaned data types and a summary of the first few rows
superstore_data.dtypes, superstore_data.head()

<ipython-input-7-a2067c5e28b0>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  superstore_data['Order Date'] = pd.to_datetime(superstore_data['Order Date'], errors='coerce', dayfirst=True)
<ipython-input-7-a2067c5e28b0>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  superstore_data['Ship Date'] = pd.to_datetime(superstore_data['Ship Date'], errors='coerce', dayfirst=True)

(Row ID                    int64
 Order ID                 object
 Order Date       datetime64[ns]
 Ship Date        datetime64[ns]
 Ship Mode                object
 Customer ID              object
 Customer Name            object
 Segment                  object
 Country                  object
 City                     object
 State                    object
 Postal Code               int64
 Region                   object
 Product ID               object
 Category                 object
 Sub-Category             object
 Product Name             object
 Sales                   float64
 Quantity                  int64
 Discount                float64
 Profit                  float64
 dtype: object,
    Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
 0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
 1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
 2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
 3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
 4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

      Customer Name    Segment        Country             City  ...  \
 0      Claire Gute   Consumer  United States        Henderson  ...
 1      Claire Gute   Consumer  United States        Henderson  ...
 2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
 3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
 4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

   Postal Code  Region       Product ID         Category Sub-Category  \
 0       42420   South  FUR-BO-10001798        Furniture    Bookcases
 1       42420   South  FUR-CH-10000454        Furniture       Chairs
 2       90036    West  OFF-LA-10000240  Office Supplies       Labels
 3       33311   South  FUR-TA-10000577        Furniture       Tables
 4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                         Product Name     Sales  Quantity  \
 0                  Bush Somerset Collection Bookcase  261.9600         2
 1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
 2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
 3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
 4                     Eldon Fold 'N Roll Cart System   22.3680         2

    Discount    Profit
 0      0.00   41.9136
 1      0.00  219.5820
 2      0.00    6.8714
 3      0.45 -383.0310
 4      0.20    2.5164

 [5 rows x 21 columns])

In [ ]:
superstore_data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### Handling missing values and outliers
- Check for and address any missing values in critical columns.
- Identify outliers in numerical columns.

In [ ]:
# Check for missing values in the dataset
missing_values = superstore_data.isnull().sum()

# Display basic statistics to identify any potential outliers
# This will help us understand the range and identify extreme values in numerical columns
numerical_summary = superstore_data[['Sales', 'Profit', 'Discount', 'Quantity']].describe()

missing_values, numerical_summary

# Handling Outliers in 'Sales' and 'Profit' by capping to the 1st and 99th percentiles
# Define the 1st and 99th percentile values for capping
sales_lower, sales_upper = superstore_data['Sales'].quantile([0.01, 0.99])
profit_lower, profit_upper = superstore_data['Profit'].quantile([0.01, 0.99])

# Cap the outliers
superstore_data['Sales'] = superstore_data['Sales'].clip(lower=sales_lower, upper=sales_upper)
superstore_data['Profit'] = superstore_data['Profit'].clip(lower=profit_lower, upper=profit_upper)

## Feature Engineering
Create useful new columns:
- Order Month
- Order Year
- Order Processing Time
- Discounted Orders
- High-Cost and Low-Cost Orders

In [ ]:
# Feature Engineering - Create new columns
# 'Order Month' and 'Order Year' based on 'Order Date'
superstore_data['Order Month'] = superstore_data['Order Date'].dt.month
superstore_data['Order Year'] = superstore_data['Order Date'].dt.year

# Order Processing Time - Calculate the number of days between Order Date and Ship Date
superstore_data['Processing Time'] = (superstore_data['Ship Date'] - superstore_data['Order Date']).dt.days

# Profit Margin - Calculate as a percentage of Sales
superstore_data['Profit Margin'] = (superstore_data['Profit'] / superstore_data['Sales']) * 100

# Discounted Orders - Create a binary indicator for orders with discounts
superstore_data['Discounted Order'] = superstore_data['Discount'].apply(lambda x: 1 if x > 0 else 0)

# High-Cost and Low-Cost Orders - Categorize orders based on Sales percentiles
sales_25th, sales_75th = superstore_data['Sales'].quantile([0.25, 0.75])
superstore_data['Order Cost Category'] = superstore_data['Sales'].apply(lambda x: 'Low-Cost' if x < sales_25th
                                                                        else ('High-Cost' if x > sales_75th else 'Medium-Cost'))

# Verify the results by showing data types and a sample of the updated data
superstore_data.dtypes, superstore_data[['Sales', 'Profit', 'Order Month', 'Order Year',
                                         'Processing Time', 'Profit Margin', 'Discounted Order', 'Order Cost Category']].head()

(Row ID                          int64
 Order ID                       object
 Order Date             datetime64[ns]
 Ship Date              datetime64[ns]
 Ship Mode                      object
 Customer ID                    object
 Customer Name                  object
 Segment                        object
 Country                        object
 City                           object
 State                          object
 Postal Code                     int64
 Region                         object
 Product ID                     object
 Category                       object
 Sub-Category                   object
 Product Name                   object
 Sales                         float64
 Quantity                        int64
 Discount                      float64
 Profit                        float64
 Order Month                     int32
 Order Year                      int32
 Processing Time                 int64
 Profit Margin                 float64
 Discounted Order                int64
 Order Cost Category            object
 dtype: object,
       Sales      Profit  Order Month  Order Year  Processing Time  \
 0  261.9600   41.913600           11        2016                3
 1  731.9400  219.582000           11        2016                3
 2   14.6200    6.871400            6        2016                4
 3  957.5775 -319.264953           10        2015                7
 4   22.3680    2.516400           10        2015                7

    Profit Margin  Discounted Order Order Cost Category
 0        16.0000                 0           High-Cost
 1        30.0000                 0           High-Cost
 2        47.0000                 0            Low-Cost
 3       -33.3409                 1           High-Cost
 4        11.2500                 1         Medium-Cost  )

In [ ]:
# Save the dataframe to a new CSV file after feature engineering
superstore_data.to_csv("superstore_data.csv", index=False)
print("Data saved")

Data saved

In [ ]:
superstore_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Row ID               9994 non-null   int64
 1   Order ID             9994 non-null   object
 2   Order Date           9994 non-null   datetime64[ns]
 3   Ship Date            9994 non-null   datetime64[ns]
 4   Ship Mode            9994 non-null   object
 5   Customer ID          9994 non-null   object
 6   Customer Name        9994 non-null   object
 7   Segment              9994 non-null   object
 8   Country              9994 non-null   object
 9   City                 9994 non-null   object
 10  State                9994 non-null   object
 11  Postal Code          9994 non-null   int64
 12  Region               9994 non-null   object
 13  Product ID           9994 non-null   object
 14  Category             9994 non-null   object
 15  Sub-Category         9994 non-null   object
 16  Product Name         9994 non-null   object
 17  Sales                9994 non-null   float64
 18  Quantity             9994 non-null   int64
 19  Discount             9994 non-null   float64
 20  Profit               9994 non-null   float64
 21  Order Month          9994 non-null   int32
 22  Order Year           9994 non-null   int32
 23  Processing Time      9994 non-null   int64
 24  Profit Margin        9994 non-null   float64
 25  Discounted Order     9994 non-null   int64
 26  Order Cost Category  9994 non-null   object
dtypes: datetime64[ns](2), float64(4), int32(2), int64(5), object(14)
memory usage: 2.0+ MB

## Categorical encoding and Data Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

# Define the columns to be encoded and scaled
categorical_cols = ['Ship Mode', 'Segment', 'Order Cost Category']
numerical_cols = ['Sales', 'Profit', 'Discount', 'Quantity', 'Processing Time', 'Profit Margin']

# OneHotEncode categorical columns, and scale numerical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(drop='first'), categorical_cols)
    ])

# Apply the transformations to the entire dataset
processed_data = preprocessor.fit_transform(superstore_data)

# Convert processed data to a DataFrame for better readability
# Retrieve feature names after encoding
encoded_features = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols)
all_features = numerical_cols + list(encoded_features)

# Create a DataFrame for the transformed data
processed_df = pd.DataFrame(processed_data, columns=all_features, index=superstore_data.index)

# Concatenate the original dataset (excluding columns to be transformed) with the new features
final_data = pd.concat([superstore_data.drop(columns=categorical_cols + numerical_cols), processed_df], axis=1)

# Display the first few rows of the updated dataset
final_data.head()

,Row ID,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Country,City,State,Postal Code,...,Quantity,Processing Time,Profit Margin,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Segment_Corporate,Segment_Home Office,Order Cost Category_Low-Cost,Order Cost Category_Medium-Cost
0,1,CA-2016-152156,2016-11-08,2016-11-11,CG-12520,Claire Gute,United States,Henderson,Kentucky,42420,...,-0.804303,-0.548318,0.075677,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,CA-2016-152156,2016-11-08,2016-11-11,CG-12520,Claire Gute,United States,Henderson,Kentucky,42420,...,-0.354865,-0.548318,0.389002,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,CA-2016-138688,2016-06-12,2016-06-16,DV-13045,Darrin Van Huff,United States,Los Angeles,California,90036,...,-0.804303,0.023935,0.769467,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,4,US-2015-108966,2015-10-11,2015-10-18,SO-20335,Sean O'Donnell,United States,Fort Lauderdale,Florida,33311,...,0.544012,1.740693,-1.028588,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5,US-2015-108966,2015-10-11,2015-10-18,SO-20335,Sean O'Donnell,United States,Fort Lauderdale,Florida,33311,...,-0.804303,1.740693,-0.030629,0.0,0.0,1.0,0.0,0.0,0.0,1.0

**Explanation:** This step prepares the dataset for machine learning by ensuring all features are numerical and scaled appropriately.

In [ ]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Row ID                           9994 non-null   int64
 1   Order ID                         9994 non-null   object
 2   Order Date                       9994 non-null   datetime64[ns]
 3   Ship Date                        9994 non-null   datetime64[ns]
 4   Customer ID                      9994 non-null   object
 5   Customer Name                    9994 non-null   object
 6   Country                          9994 non-null   object
 7   City                             9994 non-null   object
 8   State                            9994 non-null   object
 9   Postal Code                      9994 non-null   int64
 10  Region                           9994 non-null   object
 11  Product ID                       9994 non-null   object
 12  Category                         9994 non-null   object
 13  Sub-Category                     9994 non-null   object
 14  Product Name                     9994 non-null   object
 15  Order Month                      9994 non-null   int32
 16  Order Year                       9994 non-null   int32
 17  Discounted Order                 9994 non-null   int64
 18  Sales                            9994 non-null   float64
 19  Profit                           9994 non-null   float64
 20  Discount                         9994 non-null   float64
 21  Quantity                         9994 non-null   float64
 22  Processing Time                  9994 non-null   float64
 23  Profit Margin                    9994 non-null   float64
 24  Ship Mode_Same Day               9994 non-null   float64
 25  Ship Mode_Second Class           9994 non-null   float64
 26  Ship Mode_Standard Class         9994 non-null   float64
 27  Segment_Corporate                9994 non-null   float64
 28  Segment_Home Office              9994 non-null   float64
 29  Order Cost Category_Low-Cost     9994 non-null   float64
 30  Order Cost Category_Medium-Cost  9994 non-null   float64
dtypes: datetime64[ns](2), float64(13), int32(2), int64(3), object(11)
memory usage: 2.3+ MB

In [ ]:
# Save the dataframe to a new CSV file after scaling
final_data.to_csv("superstore_data_for_ml.csv", index=False)
print("Data saved")

Data saved